### ISSUE TITLE
How do you get all this data?

### ISSUE THREAD

**Issue by LuisPzMarin** [nilesh7patel86/scratchpad#1]
I am developing an application for calculate dfferents configurations for Lord Mobile and this data is so usefull, but its difficult to work. Could you tell me how do you get it?

Thanks in advance

**Comment by nilesh7patel86** [comment]
I prepared that manually from the game itself, but you can take a look at [LM Fandom](https://lordsmobile.fandom.com/wiki/Main_Page), it's a good source.
